version: "3.8"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=bookingDB
    volumes:
      - mongo-data:/data/db
  api:
    build: ./gouland
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bookingDB
      - JWT_SECRET=changeme
    depends_on:
      - mongo
    volumes:
      - ./gouland:/app
      - mongo-data:/data/db
volumes:
  mongo-data:
